customers/urls.py
from django.urls import path
from .views import customers, register, signin

app_name = "customers"

urlpatterns = [
    path("", customers, name = "customersView"), 
    path("register/", register, name = "registerView"),
    path("signin/", signin, name = "signinView"),
]

home/urls.py
from django.urls import path
from .views import home, about, contact

app_name = "home"

urlpatterns = [
    path("", home, name = "homeView"), 
    path("about/", about, name = "aboutView"),
    path("contact/", contact, name = "contactView"),
]

medihome/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('customers/', include('customers.urls')),
]

customers/models.py
from django.db import models


# Create your models here.

class People(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    gender = models.CharField(max_length = 10)
    user_Address = models.ForeignKey("Address", on_delete = models.CASCADE, default = 1)
    user_doc = models.ForeignKey("Doctor", on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.first_name

class Address(models.Model):
    Home_Address = models.CharField(max_length = 500)
    State = models.CharField(max_length = 100, default = 1)
    Country = models.CharField(max_length = 70)
    Telephone = models.CharField(max_length = 70, default = 1)

    def __str__(self):
       return str(self.State)

class Doctor(models.Model):
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    gender = models.CharField(max_length = 10)
    office_address = models.CharField(max_length = 100)

    def __str__(self):
       return str(self.first_name)
     

class Product(models.Model):
    product_name = models.CharField(max_length = 50)
    product_maker = models.CharField(max_length = 50)
    product_price = models.CharField(max_length = 50)
    product_country = models.CharField(max_length = 10)

    def __str__(self):
        return self.product_name

class Bio(models.Model):
    user_profile = models.OneToOneField(People, on_delete=models.CASCADE)
    profession = models.CharField(max_length = 50)
    nationality = models.CharField(max_length = 50)
    degree = models.CharField(max_length = 50)
    user_email = models.EmailField(max_length=200)

    def __str__(self):
        return str(self.user_profile)

home/models.py
from django.db import models

# Create your models here.

customers/views.py
from django.shortcuts import render, redirect

# Create your views here.

def customers(request):
    return render(request, "customers/ourcare.html")

def register(request):
    return render(request, "customers/register.html")

def signin (request):
    return render(request, "customers/signin.html")

home/views.py
from django.shortcuts import render,redirect

# Create your views here.

def home(request):
    return render(request, "home/index.html")


def about(request):
    return render(request, "home/about.html")

def contact (request):
    return render(request, "home/contact.html")

customers/templates/customers/ourcare.html
{% extends 'home\index.html'%}


	{% block body %}
	<div class="banner-inner">
	</div>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="index.html">Home</a>
		</li>
		<li class="breadcrumb-item active">Blog1</li>
	</ol>
	<!--//banner-->

	<!--/main-->
	<section class="main-content-w3layouts-agileits">
		<div class="container">
			<h3 class="tittle">Blog Posts</h3>
			<div class="row inner-sec">
				<!--left-->
				<div class="col-lg-8 left-blog-info-w3layouts-agileits text-left">
					<article class="blog-grid-top">
						<div class="b-grid-top">
							<div class="blog_info_left_grid">
								<a href="single.html">
									<img src="images/b1.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="blog-info-middle">
								<ul>
									<li>
										<a href="#">
											<i class="far fa-calendar-alt"></i> FEB 15,2018</a>
									</li>
									<li class="mx-2">
										<a href="#">
											<i class="far fa-thumbs-up"></i> 201 Likes</a>
									</li>
									<li>
										<a href="#">
											<i class="far fa-comment"></i> 15 Comments</a>
									</li>

								</ul>
							</div>
						</div>

						<h3>
							<a href="single.html">Amet consectetur adipisicing </a>
						</h3>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt ut labore et dolore magna
							aliqua uta enim ad minim ven iam quis nostrud exercitation ullamco labor nisi ut aliquip exea commodo consequat duis
							aute irudre dolor in elit sed uta labore dolore reprehender</p>
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</article>
					<article class="blog-grid-top my-5">
						<div class="b-grid-top">
							<div class="blog_info_left_grid">
								<a href="single.html">
									<img src="images/b4.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="blog-info-middle">
								<ul>
									<li>
										<a href="#">
											<i class="far fa-calendar-alt"></i> FEB 15,2018</a>
									</li>
									<li class="mx-2">
										<a href="#">
											<i class="far fa-thumbs-up"></i> 201 Likes</a>
									</li>
									<li>
										<a href="#">
											<i class="far fa-comment"></i> 15 Comments</a>
									</li>

								</ul>
							</div>
						</div>

						<h3>
							<a href="single.html">Amet consectetur adipisicing </a>
						</h3>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt ut labore et dolore magna
							aliqua uta enim ad minim ven iam quis nostrud exercitation ullamco labor nisi ut aliquip exea commodo consequat duis
							aute irudre dolor in elit sed uta labore dolore reprehender</p>
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</article>
					<article class="blog-grid-top mb-4">
						<div class="b-grid-top">
							<div class="blog_info_left_grid">
								<a href="single.html">
									<img src="images/b1.jpg" class="img-fluid" alt="">
								</a>
							</div>
							<div class="blog-info-middle">
								<ul>
									<li>
										<a href="#">
											<i class="far fa-calendar-alt"></i> FEB 15,2018</a>
									</li>
									<li class="mx-2">
										<a href="#">
											<i class="far fa-thumbs-up"></i> 201 Likes</a>
									</li>
									<li>
										<a href="#">
											<i class="far fa-comment"></i> 15 Comments</a>
									</li>

								</ul>
							</div>
						</div>

						<h3>
							<a href="single.html">Amet consectetur adipisicing </a>
						</h3>
						<p>Lorem ipsum dolor sit amet consectetur adipisicing elit sedc dnmo eiusmod tempor incididunt ut labore et dolore magna
							aliqua uta enim ad minim ven iam quis nostrud exercitation ullamco labor nisi ut aliquip exea commodo consequat duis
							aute irudre dolor in elit sed uta labore dolore reprehender</p>
						<a href="single.html" class="btn btn-primary read-m">Read More</a>
					</article>
					<nav aria-label="Page navigation example">
						<ul class="pagination justify-content-left">
							<li class="page-item disabled">
								<a class="page-link" href="#" tabindex="-1">Previous</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">1</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">2</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">3</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="#">Next</a>
							</li>
						</ul>
					</nav>
				</div>
				<!--//left-->
				<!--right-->
				<aside class="col-lg-4 agileits-w3ls-right-blog-con text-left">
					<div class="right-blog-info text-left">
						<div class="tech-btm">
							<img src="images/banner1.jpg" class="img-fluid" alt="">
						</div>
						<div class="tech-btm">
							<h4>Sign up to our newsletter</h4>
							<p>Pellentesque dui, non felis. Maecenas male </p>
							<form action="#" method="post">
								<input type="email" placeholder="Email" required="">
								<input type="submit" value="Subscribe">
							</form>

						</div>
						<div class="tech-btm">
							<h4>Categories</h4>
							<ul class="list-group single">
								<li class="list-group-item d-flex justify-content-between align-items-center">
									Cras justo odio
									<span class="badge badge-primary badge-pill">14</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center">
									Dapibus ac facilisis in
									<span class="badge badge-primary badge-pill">2</span>
								</li>
								<li class="list-group-item d-flex justify-content-between align-items-center">
									Morbi leo risus
									<span class="badge badge-primary badge-pill">1</span>
								</li>
							</ul>
						</div>
						<div class="tech-btm">
							<h4>Top stories of the week</h4>

							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/1.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>

							</div>
							<div class="blog-grids row mb-3">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/6.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">
									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Feb, 2018</span>
									</div>
								</div>

							</div>
						</div>
						<div class="single-gd my-5 tech-btm">
							<h4>Our Progress</h4>
							<div class="progress">
								<div class="progress-bar progress-bar-striped" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0"
								    aria-valuemax="100"></div>
							</div>
						</div>
						<div class="single-gd tech-btm text-left">
							<h4>Recent Post</h4>
							<div class="blog-grids">
								<div class="blog-grid-left">
									<a href="single.html">
										<img src="images/b1.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male</a>
									</h5>
								</div>

							</div>
						</div>

						<div class="tech-btm widget_social text-left">
							<h4>Stay Connect</h4>
							<ul>

								<li>
									<a class="twitter" href="#">
										<i class="fab fa-twitter"></i>
										<span class="count">317K</span> Twitter Followers</a>
								</li>
								<li>
									<a class="facebook" href="#">
										<i class="fab fa-facebook-f"></i>
										<span class="count">218k</span> Twitter Followers</a>
								</li>
								<li>
									<a class="dribble" href="#">
										<i class="fab fa-dribbble"></i>

										<span class="count">215k</span> Dribble Followers</a>
								</li>
								<li>
									<a class="pin" href="#">
										<i class="fab fa-pinterest"></i>
										<span class="count">190k</span> Pinterest Followers</a>
								</li>

							</ul>
						</div>
						<div class="tech-btm">
							<h4>Recent Posts</h4>

							<div class="blog-grids row mb-3 text-left">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/1.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>

							</div>
							<div class="blog-grids row mb-3 text-left">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/5.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">

									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Jan, 2018</span>
									</div>
								</div>
								<div class="clearfix"> </div>
							</div>
							<div class="blog-grids row mb-3 text-left">
								<div class="col-md-5 blog-grid-left">
									<a href="single.html">
										<img src="images/3.jpg" class="img-fluid" alt="">
									</a>
								</div>
								<div class="col-md-7 blog-grid-right">
									<h5>
										<a href="single.html">Pellentesque dui, non felis. Maecenas male non felis </a>
									</h5>
									<div class="sub-meta">
										<span>
											<i class="far fa-clock"></i> 20 Feb, 2018</span>
									</div>
								</div>

							</div>
						</div>
					</div>
				</aside>
				<!--//right-->
			</div>
		</div>
	</section>
	<!--//main-->
	{% endblock body %}
	

customers/templates/customers/register.html
{% extends 'home\index.html'%}


	{% block body %}
	<div class="banner-inner">
	</div>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{% url 'home:homeView' %}">Home</a>
		</li>
		<li class="breadcrumb-item active">Register</li>
	</ol>
	<!--//banner-->
	<!--/main-->
	<section class="main-content-w3layouts-agileits">
		<div class="container">
			<h3 class="tittle">Register Now</h3>
				<div class="inner-sec">
			<div class="login p-5 bg-light mx-auto mw-100">
				<form action="#" method="post">
						<div class="form-row">
								<div class="col-md-6 mb-3">
										<label for="validationCustom01">First name</label>

									<input type="text" class="form-control" id="validationDefault01" placeholder="" required="">
								</div>
								<div class="col-md-6 mb-3">
										<label for="validationCustom02">Last name</label>
									<input type="text" class="form-control" id="validationDefault02" placeholder="" required="">
								</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-6">
										<label for="exampleInputPassword1 mb-2">Password</label>
									<input type="password" class="form-control" id="password1" placeholder="" required="">
								</div>
								<div class="form-group col-md-6">
										<label for="exampleInputPassword2 mb-2">Confirm Password</label>
										<input type="password" class="form-control" id="password2" placeholder="" required="">
									</div>
								
							</div>
							<button type="submit" class="btn btn-primary submit mb-4">Register</button>
								<p>
									<a href="#">By clicking Signup, I agree to your terms</a>
								</p>
						</form>
		
					</div>
			</div>
		</div>
	</section>
	{% endblock body %}
	

customers/templates/customers/signin.html
{% extends 'home\index.html'%}


	{% block body %}
	<div class="banner-inner">
	</div>
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{% url 'home:homeView' %}">Home</a>
		</li>
		<li class="breadcrumb-item active">Signin</li>
	</ol>
	<!--//banner-->
	<!--/main-->
	<section class="main-content-w3layouts-agileits">
		<div class="container">
				<h3 class="tittle">Sign In Now</h3>
				<div class="row inner-sec">
					<div class="login p-5 bg-light mx-auto mw-100">
					<form action="#" method="post">
							<div class="form-group">
							  <label for="exampleInputEmail1 mb-2">Email address</label>
							  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="" required="">
							  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
							</div>
							<div class="form-group">
							  <label for="exampleInputPassword1 mb-2">Password</label>
							  <input type="password" class="form-control" id="exampleInputPassword1" placeholder="" required="">
							</div>
							<div class="form-check mb-2">
							  <input type="checkbox" class="form-check-input" id="exampleCheck1">
							  <label class="form-check-label" for="exampleCheck1">Check me out</label>
							</div>
							<button type="submit" class="btn btn-primary submit mb-4">Sign In</button>
							<p><a href="register.html"> Don't have an account?</a></p>
						  </form>
		</div>
		</div>
	</div>
	</section>
	<!--//main-->
	<!--footer-->
	{% endblock body %}
	

home/templates/home/about.html
{% extends 'home\index.html'%}



{% block body %}
<div class="about">
	<div class="container">
		<h3 class="tittle">ABOUT</h3>
		<div class="col-md-5 about-grid-left text-center">
			<img src="images/6.jpg" alt=""/>
		</div>
		<div class="col-md-7 about-grid">
							<h4>NEQUE PORRO QUISQUAM EST, QUI </h4>
							<p>Sed ut perspiciatis unde omnis iste natus error sit 
							voluptatem accusantium doloremque laudantium, totam rem aperiam, 
							eaque ipsa quae ab illo inventore veritatis et numquam eius modi 
							tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
							Ut enim ad minima veniam, quis nostrum</p>
							<p>numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
							Ut enim ad minima veniam, quis nostrum exercitation modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
							Ut enim ad minima veniam, quis</p>
		</div>
		<div class="clearfix"></div>
	</div>
</div>
<!--about-bottom-->
<div class="about-bottom">
		<div class="container">
			<div class="about-bottom-grids">
				<div class="col-md-7 about-bottom-grid-left">
					<h3 class="tittle t-two">OUR TREATMENTS</h3>
					<h4>OPTIO CUMQUE NIHIL IMPEDIT QUO MINUS ID QUOD MAXIME PLACEAT 
						FACERE POSSIMUS, OMNIS VOLUPTAS ASSUMENDA EST, OMNIS</h4>
					<p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, 
						consectetur, adipisci velit, sed quia non numquam eius modi tempora 
						incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
						Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis 
						suscipit laboriosam.</p>
				</div>
				<div class="col-md-5 about-bottom-grid-right">
					<h3 class="tittle t-two">Testimonials</h3>
					<div class="about-bottom-grid-right-grid">
						<div class="about-bottom-grid-right-grdl">
							<img src="images/bbb.jpg" alt=" " class="img-responsive" />
						</div>
						<div class="about-bottom-grid-right-grdr">
							<p><span>N</span>eque porro quisquam est, 
								qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
								sed quia non numquam eius modi.</p>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="about-bottom-grid-right-grid">
						<div class="about-bottom-grid-right-grdl">
							<img src="images/ccc.jpg" alt=" " class="img-responsive" />
						</div>
						<div class="about-bottom-grid-right-grdr">
							<p><span>R</span>eque porro quisquam est, 
								qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
								sed quia non numquam eius modi.</p>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
<!--//about-bottom-->
<!-- contact -->
{% endblock body %}

home/templates/home/contact.html
{% extends 'home\index.html'%}



{% block body %}
<div class="contact-us">
	<div class="container">
		<h3 class="tittle">CONTACT</h3>
		<div class="contact-grids">
			<div class="col-md-4 contact-grid text-center">
				<div class="point-icon"><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span></div>
				<p>Jl. Pahlawan VII No.247-D Sidoarjo-Surabaya-Indonesia</p>
			</div>
			<div class="col-md-4 contact-grid text-center">
				<div class="point-icon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></div>
				<p><a href="mail-to:sample@example.com">rudhisasmito@gmail.com</a></p>
			</div>
			<div class="col-md-4 contact-grid text-center">
				<div class="point-icon"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span></div>
				<p>+613 0000 0000</p>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="contact-info">
			<form>
				<input type="text" placeholder="Your Name" required>
				<input type="text" placeholder="Your E-Mail" required>
				<input type="text" placeholder="Subject" required>
				<textarea placeholder="Your Message" required></textarea>
				<input type="submit" value="SEND MESSAGE">
			</form>
		</div>
	</div>
</div>
<!-- //contact-us -->
<!-- contact -->
{% endblock body %}